# Generated by Django 3.2.9 on 2021-12-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blender', '0002_criteriamodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriamodel',
            name='artist2',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='artist3',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='artist4',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='artist5',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='genre2',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='genre3',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='genre4',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='genre5',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='track2',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='track3',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='track4',
        ),
        migrations.RemoveField(
            model_name='criteriamodel',
            name='track5',
        ),
        migrations.AddField(
            model_name='criteriamodel',
            name='choice4',
            field=models.CharField(default='whatever', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteriamodel',
            name='choice5',
            field=models.CharField(default='aaaaaa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteriamodel',
            name='type4',
            field=models.CharField(choices=[('artists', 'Artist'), ('tracks', 'Track'), ('genres', 'Genre')], default='awewadw', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criteriamodel',
            name='type5',
            field=models.CharField(choices=[('artists', 'Artist'), ('tracks', 'Track'), ('genres', 'Genre')], default='awrasefa', max_length=20),
            preserve_default=False,
        ),
    ]
